backend_repo_url: "https://github.com/samuelchaba/book-review-app.git"
backend_app_port: 3001
db_host: "bookreview-dev-mysql.cvqcikgs0a79.ap-south-1.rds.amazonaws.com"
db_user: "mysqladmin"
db_password: "Password1234"
db_name: "bookreviews_dev"
jwt_secret: "your_jwt_secret"
allowed_origins: "http://13.233.167.171:3000"
